### ISSUE TITLE
#1 PRACTICA DE REQUISITOS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/practica-de-requisitos-equipo-fglr#1]
[PRACTICA_REQUISITOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-equipo-fglr/files/7558276/PRACTICA_REQUISITOS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación 28/ 30

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143172248-cf5fc618-f9ab-49ff-9c1a-7d46a1e7b1c6.png)
Esta lista de requerimientos se debe mejorar en su redacción.

**Comment by josealfredo79** [comment]
Falta la lista de requerimientos No Funcionales

**Comment by josealfredo79** [comment]
Deben mejorar la practica

**Comment by josealfredo79** [comment]
Ejemplo de requerimiento funcional Brindar informacion al usuario para utilizar el sistema

**Comment by josealfredo79** [comment]
Registrar usuario
Iniciar sesión con usuario
Actualizar usuario 
Actualizar suscripción

**Comment by Rmz-Rigo** [comment]
[PRACTICA_REQUISITOS_CORREGIDO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-equipo-fglr/files/7605270/PRACTICA_REQUISITOS_CORREGIDO.pdf)

**Comment by Rmz-Rigo** [comment]
Buenas tardes ing, ya agregamos y corregimos lo que nos indicó, gracias.

**Comment by josealfredo79** [comment]
ya negociaron los requisitos????

**Comment by josealfredo79** [comment]
Bien hecho y revisado
